### ISSUE TITLE
Can i add my code for linked list and sorting in c language. And is this reppsitory acceptable for hacktoberfest.

### ISSUE THREAD

**Issue by ItsMeVikashKumarSingh** [bosc-official/all_in_one_C_Programs#4]
Can i add my code for linked list and sorting in c language. And is this reppsitory acceptable for hacktoberfest

**Comment by b0sc** [comment]
Of course, but be sure to include each program in separate files, the main program file has already become bulky and difficult to manage. It is acceptable for hacktoberfest, be sure to read readme file.

**Comment by ItsMeVikashKumarSingh** [comment]
As per guidelines i added the code. Please merge my pull request
